<template>
    <div>
      <input type="file" @change="handleFileUpload">
    </div>
  </template>
  <script>
  import 'firebase/firestore'
  import csvtojson from 'csvtojson'
  import { collection, addDoc, firebaseStore } from '../firebase/database.js'
  
  export default {
    methods: {
      async handleFileUpload(event) {
        const file = event.target.files[0]
        const reader = new FileReader()
        reader.readAsText(file)
        reader.onload = async (event) => {
          const csvData = event.target.result
          const jsonData = await csvtojson({
            noheader: true,
            trim: true,
            delimiter: ',',
            checkType: true,
            ignoreEmpty: true,
            headers: [
              "ledv",
"lesv",
"lsv",
"lvef",
"lvmass",
"redv",
"resv",
"rsv",
"rvef",
"scar",
"AnteriorVentJunction",
"InferiorVentJunction",
"BothVentJunction",
"SubendoScar",
"MesoScar",
"EpicardScar",
"BifidAL",
"BifidPostMed",
"TwoBifidPM",
"ApicallyDisplacedAL",
"lge49",
"lge51",
"scarseg",
"female",
"AgeatMRI",
"bsa",
"ApicalHCM",
"Indeterminateconcentricandal",
"SigmoidProxseptHCM",
"ReverseCurve",
"VUS",
"MYH7",
"MYBPC3mutation",
"TNNT2mutation",
"ACTCmutation",
"TPM1",
"LAMP2",
"TNNCI",
"TNNI3",
"DES",
"MYL2",
"TTR",
"ALMS1",
"TTN",
"core",
"gray",
"total",
"nonviable",
"wall",
"Hospitalization",
"Datehositalized",
"UplannedHospitalization",
"ReasonforHospitalization",
"SustainedVT",
"DateofSustainedVT",
"ICD",
"ICDFiring",
"DateICDFired",
"HeartAttack",
"HeartAttackDate",
"NonCardiacDeath",
"DateNonCardiacDeath",
"SuddenCardiacDeath",
"SuddenCardiacDeathDate",
"CardiovascularDeath",
"transplant",
"Arrhythmiaoutcome",
"Hyperlipidemia",
"Hypertension",
"Diabetes",
"Myectomy",
"Myectomydate",
"Alcoholseptalablation",
"CCB",
"ACEI",
"BBlocker",
"Statin",
"Antiarrhythmic",
"ARB",
"AldoAntag",
"DQ",
"NSVT",
"Hypotension",
"LVWT",
"FHSCD",
"HxSCDVT",
"Syncope",
"RestgradmmHg",
"restgrad30",
"CPXVO2max",
"RFs",
"deceased",
"thosp",
"tvt",
"fuvt",
"ficd",
"dead",
"tdead",
"fudead",
"ttrans",
"futrans",
"tmyect",
"fumyect",
"tabl",
"fuabl",
"syncope",
"testing",
"fut",
"futy",
"lvmi",
"mys",
"lvh",
"lvh30",
"myh",
"mybp",
"tnn",
"other",
"lvedvi",
"lvesvi",
"lvsvi",
"rvf",
"redvvi",
"resvi",
"rvsvi",
"vus",
"followt",
"futime",
"myabls",
"futmyect",
"futdead",
"hyperlipidemia_Dx",
"hypertension",
"diabe",
"largescar",
"scar5",
"futicd",
"mys2",
"myh2",
"mybp2",
"vus2",
"other2",
"lowef",
"vus3",
"Genemut2",
"vus4",
"myh3",
"mybp3",
"other3",
"mys3",
"nogene"
            ]
          }).fromString(csvData)
          const collectionRef = collection(firebaseStore,'hcms')
          jsonData.forEach(async (data) => {
await addDoc(collectionRef,data);})
        }
      }
    }
  }
  </script>